cc_library(
    name = "schema",
    srcs = glob([
        "*.c++",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    deps = [
        "//capnproto/capnp",
    ],
    linkstatic = 1,
    visibility = ["//visibility:public"],
)
