cc_binary(
    name = "main",
    srcs = [
        "main.cpp",
        "addressbook.capnp.h",
        "addressbook.capnp.c++",
    ],
    deps = [
        "//uWebSockets",
        "//lmdb/lmdb",
        "//capnproto/capnp",
        "//s2",
    ],
)
